Fix the module not being able to set the DM flag because Synapse gives frozen data in response to `get_global`.
matrix-org/synapse-auto-accept-invite pull request #11
Opened 2022-05-25 10:55 UTC by reivilibre

2022-05-25 15:00 UTC, anoadragon453 requested changes
lightning review :zap:

2022-05-25 15:10 UTC, reivilibre commented on synapse_auto_accept_invite/__init__.py
> +        dm_map: Dict[str, Tuple[str, ...]] = dict(
Aye, that's why I do the awkward `tuple(...) + (x,)` thing below to append. Maybe we should've just cloned all the data we pass out of the module API, it's a bit messy and error prone, but oh well :/

2022-05-26 13:54 UTC, anoadragon453 approved these changes
lgtm!

2022-05-26 13:54 UTC, anoadragon453 commented on synapse_auto_accept_invite/__init__.py
> +        dm_map: Dict[str, Tuple[str, ...]] = dict(
> Maybe we should've just cloned all the data we pass out of the module API

I can see arguments for doing both... At least it fails loudly :)

2022-05-26 13:56 UTC, merged